spring:
  datasource:
    username: root
    password: TNv5cleLDezzhlW+r804fQSskW0JoWwv84QKfjyQOA298421C2B++tqHLAwRjpleJ336v+8VcCkP3oSR5sGhAA==
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.38.228:3306/jc-club?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&AllowPublicKeyRetrieval=True
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: abc123
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true

publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAImASxnVV3YH9sEkIfVB2PO3U1lT9Nbi3WhCxY2rMrA/nX7J3cm+G8r4ZIgAqFm3ODf/sBrcfzXdk5GoKeu4X2kCAwEAAQ==

logging:
  config: classpath:log4j2-spring.xml

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
